name: docker_to_docker_comunication

services:
  receiver:
    container_name: receiver
    hostname: receiver
    networks:
      - default
    volumes:
      - receiver_volume:/local_bind
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=UTC
    build: .
    command: ["bash", "-c", "
      echo 'Receiver initialized'; 
      ./run_receiver.sh;
      sleep infinity;
      "]

  sender:
    container_name: sender
    hostname: sender
    networks:
      - default
    volumes:
      - sender_volume:/local_bind
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=UTC
      - RECEIVER_IP=receiver
    depends_on:
      - receiver
    build: .
    command: ["bash", "-c", "
      echo 'Sender initialized'; 
      ./run_sender.sh;
      ./run_formatter.sh;
      sleep infinity; 
      "]

volumes:
  receiver_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./host_volume
  sender_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./host_volume
    
networks:
  default:
    driver: bridge





